version: "3.3"

services:
    postgres:
        container_name: nj_consent_postgres
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
        networks:
            - djangonetwork
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - postgres
        networks:
            - djangonetwork
networks:
  djangonetwork:
      driver: bridge