# Generated by Django 4.0.4 on 2022-05-02 13:29

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_location', models.CharField(choices=[('Atlanta, GA', 'Atlanta, GA'), ('Boston, MA', 'Boston, MA'), ('Chicago, IL', 'Chicago, IL'), ('Dallas, TX', 'Dallas, TX'), ('Denver, CO', 'Denver, CO'), ('Farmington, CT', 'Farmington, CT'), ('Houston, TX', 'Houston, TX'), ('Los Angeles, CA', 'Los Angeles, CA'), ('Miami, FL', 'Miami, FL'), ('New York, NY', 'New York, NY'), ('Philadelphia, PA', 'Philadelphia, PA'), ('San Francisco, CA', 'San Francisco, CA')], default='Atlanta, GA', max_length=20)),
                ('first_name', models.CharField(max_length=130, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=130, verbose_name='Last Name')),
                ('birth_date', models.DateField()),
                ('address1', models.CharField(max_length=1024, verbose_name='Home Address (Not a PO Box)')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(max_length=2, verbose_name='State')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('NonBinary', 'NonBinary'), ('Prefer not to answer', 'Prefer not to answer')], default='Male', max_length=20)),
                ('race', models.CharField(choices=[('American Indian/Alaskan Native', 'American Indian/Alaskan Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hawaiian Native or Other Pacific Islander', 'Hawaiian Native or Other Pacific Islander'), ('White', 'White'), ('Not Stated', 'Not Stated')], default='American Indian/Alaskan Native', max_length=50)),
                ('hispanic_latino', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Yes', max_length=20, verbose_name='Hispanic/Latino')),
                ('signature_name', models.CharField(max_length=260)),
                ('date', models.DateField()),
            ],
        ),
    ]
