# Generated by Django 4.0.4 on 2022-05-03 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NjSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nj_school_name',
            },
        ),
        migrations.CreateModel(
            name='NjSchoolCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_county', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nj_school_county',
            },
        ),
        migrations.CreateModel(
            name='NjSchoolDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_district', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nj_school_district',
            },
        ),
        migrations.CreateModel(
            name='NjWorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nj_work_location',
            },
        ),
        migrations.AlterField(
            model_name='consent',
            name='work_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.njworklocation'),
        ),
    ]
