# Generated by Django 4.0.4 on 2022-05-04 10:22

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_njschool_njschoolcounty_njschooldistrict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NjConsentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=130, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('NonBinary', 'NonBinary'), ('Prefer not to answer', 'Prefer not to answer')], default='Male', max_length=20)),
                ('consenter_type', models.CharField(choices=[('student', 'student'), ('staff', 'staff')], max_length=20)),
                ('test_taker_dob', models.DateField()),
                ('address1', models.CharField(max_length=1024, verbose_name='Home Address (Not a PO Box)')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(max_length=2, verbose_name='State')),
                ('race', models.CharField(choices=[('American Indian/Alaskan Native', 'American Indian/Alaskan Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hawaiian Native or Other Pacific Islander', 'Hawaiian Native or Other Pacific Islander'), ('White', 'White'), ('Not Stated', 'Not Stated')], default='American Indian/Alaskan Native', max_length=50)),
                ('ethnicity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Yes', max_length=20, verbose_name='Hispanic/Latino')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('signature_name', models.CharField(max_length=260)),
                ('date', models.DateField()),
                ('school_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.njschoolcounty')),
                ('school_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.njschooldistrict')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.njschool')),
            ],
        ),
    ]
